source 'https://rubygems.org'

#gem "bundler", "~> 2.1.4"
gem "jekyll" #, "~> 4.3.3" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

gem "just-the-docs"